[31m[1mERROR   [0m !!--!!is_insyfficient_balance:location_withdrawal_cp.py:469 name 'row' is not defined